package com.f2pstarhunt.stars.model;

public enum StarLocation {

    WILDERNESS_RUNITE_MINE,
    WILDERNESS_CENTRE_MINE,
    WILDERNESS_SOUTH_WEST_MINE,
    WILDERNESS_SOUTH_MINE,

    DWARVEN_MINE,
    MINING_GUILD,
    CRAFTING_GUILD,
    RIMMINGTON_MINE,

    DRAYNOR_VILLAGE_BANK,
    LUMBRIDGE_SWAMP_SOUTH_WEST_MINE,
    LUMBRIDGE_SWAMP_SOUTH_EAST_MINE,

    VARROCK_SOUTH_WEST_MINE,
    VARROCK_SOUTH_EAST_MINE,
    VARROCK_AUBURY,

    AL_KHARID_MINE,
    AL_KHARID_BANK,
    PVP_ARENA,

    CRANDOR_NORTH_MINE,
    CRANDOR_SOUTH_MINE,
    CORSAIR_COVE_BANK,
    CORSAIR_COVE_RESOURCE_AREA;

}
